# Generated by Django 6.0.6 on 2026-06-24 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('medical_student', 'Medical student'), ('plab', 'PLAB candidate'), ('ukmla', 'UKMLA candidate'), ('doctor', 'Doctor'), ('tutor', 'Tutor'), ('other', 'Other')], default='other', max_length=50)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('student', 'Student'), ('pro', 'Pro')], default='free', max_length=30)),
                ('payg_credits', models.PositiveIntegerField(default=0)),
                ('real_consultation_credits', models.PositiveIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
