# Generated by MedEcho AI phase 11B fix

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(
                choices=[
                    ("none", "No title"),
                    ("dr", "Dr"),
                    ("nurse", "Nurse"),
                    ("midwife", "Midwife"),
                    ("physiotherapist", "Physiotherapist"),
                    ("paramedic", "Paramedic"),
                    ("pharmacist", "Pharmacist"),
                    ("student", "Student"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=models.CharField(
                choices=[
                    ("medical_student", "Medical student"),
                    ("foundation_doctor", "Foundation doctor / FY1-FY2"),
                    ("doctor_in_training", "Doctor in training / SHO level"),
                    ("nurse", "Nurse"),
                    ("midwife", "Midwife"),
                    ("physiotherapist", "Physiotherapist"),
                    ("paramedic", "Paramedic"),
                    ("pharmacist", "Pharmacist"),
                    ("advanced_practitioner", "Advanced practitioner"),
                    ("other_healthcare_professional", "Other healthcare professional"),
                    ("plab", "PLAB candidate"),
                    ("ukmla", "UKMLA candidate"),
                    ("doctor", "Doctor"),
                    ("tutor", "Tutor"),
                    ("other", "Other"),
                ],
                default="other_healthcare_professional",
                max_length=50,
            ),
        ),
    ]
