# Generated by Django 6.0.6 on 2026-06-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('presenting_complaint', models.CharField(blank=True, max_length=255)),
                ('hidden_diagnosis', models.CharField(blank=True, max_length=255)),
                ('case_summary', models.TextField(blank=True)),
                ('secret_prompt', models.TextField(blank=True)),
                ('voice_style', models.CharField(default='neutral_adult', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='active', max_length=30)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('differentials', models.TextField(blank=True)),
                ('investigation_interpretation', models.TextField(blank=True)),
                ('management_plan', models.TextField(blank=True)),
                ('safety_netting', models.TextField(blank=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('data_gathering_score', models.PositiveIntegerField(blank=True, null=True)),
                ('clinical_reasoning_score', models.PositiveIntegerField(blank=True, null=True)),
                ('management_score', models.PositiveIntegerField(blank=True, null=True)),
                ('ips_score', models.PositiveIntegerField(blank=True, null=True)),
                ('safety_netting_score', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('data_gathering_feedback', models.TextField(blank=True)),
                ('clinical_reasoning_feedback', models.TextField(blank=True)),
                ('management_feedback', models.TextField(blank=True)),
                ('ips_feedback', models.TextField(blank=True)),
                ('safety_netting_feedback', models.TextField(blank=True)),
                ('critical_misses', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvement_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('investigation', 'Investigation'), ('system', 'System')], max_length=30)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('voice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='investigations/')),
                ('image_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.clinicalcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealConsultationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='setup', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=480)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('real_consultation_credit_charged', models.BooleanField(default=False)),
                ('transcription_seconds_used', models.PositiveIntegerField(default=0)),
                ('input_tokens_used', models.PositiveIntegerField(default=0)),
                ('output_tokens_used', models.PositiveIntegerField(default=0)),
                ('voice_characters_used', models.PositiveIntegerField(default=0)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_consultation_sessions', to='cases.clinicalcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_consultation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('text_case', 'Text case'), ('voice_generation', 'Voice generation'), ('image_investigation', 'Image investigation'), ('real_consultation_started', 'Real consultation started'), ('real_consultation_completed', 'Real consultation completed')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
                ('clinical_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='cases.clinicalcase')),
                ('encounter_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='cases.encountermessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='cases_caseu_user_id_a559cb_idx'), models.Index(fields=['event_type', 'created_at'], name='cases_caseu_event_t_91eb97_idx')],
            },
        ),
    ]
